### ISSUE TITLE
Find out why progress' package TestFail fails (mostly) on Travis

### ISSUE THREAD

**Issue by henvic** [wedeploy/cli#31]
Sometimes it runs fine, but mostly it fails like this:

```
=== RUN   TestFail
--- FAIL: TestFail (0.07s)
panic: close of closed channel [recovered]
	panic: close of closed channel
goroutine 18 [running]:
panic(0x6e1820, 0xc820017290)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8200e2000)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:467 +0x192
panic(0x6e1820, 0xc820017290)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
github.com/henvic/uiprogress.(*Progress).Stop(0xc82001c2a0)
	/home/travis/gopath/src/github.com/henvic/uiprogress/progress.go:133 +0x37
github.com/launchpad-project/cli/progress.Stop()
	/home/travis/gopath/src/github.com/launchpad-project/cli/progress/progress.go:50 +0x3a
github.com/launchpad-project/cli/progress.TestFail(0xc8200e2000)
	/home/travis/gopath/src/github.com/launchpad-project/cli/progress/progress_test.go:101 +0x1c6
testing.tRunner(0xc8200e2000, 0x9b95f8)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0x892
FAIL	github.com/launchpad-project/cli/progress	0.166s
```

I have tried debugging by ssh-ing Travis with no success because when I run the tests there it... Always work.

Maybe some environmental change related to interactive / noninteractive? I don't know, but it doesn't seem to be worth looking anymore. Let's just skip this test for now until some later date.

**Comment by henvic** [comment]
Test started to fail (and stopped to fail afterwards) apparently for no reason today on OS X with the same odd behavior. Skipping it.

**Comment by henvic** [comment]
Not using progress bar anywhere currently and no idea if am going to use anytime soon.
